image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regsecret

resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  host: example.com
  path: /
