nameOverride: ""
fullnameOverride: ""

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

replicas: 1

imagePullSecrets:
  - name: regsecret

resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
tolerations: []

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  host: example.com
  path: /
  pathType: ImplementationSpecific
